server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://rc-project.cmqrvudhyers.ap-northeast-2.rds.amazonaws.com/zigzag?autoReconnect=true&verifyServerCertificate=false&useSSL=false # 변경해주세요
    username: qwer1234 # 변경해주세요
    password: asdf1234! # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전